name: "Setup"
description: "Setup Environment"

runs:
  using: composite
  steps:
    - name: Install node v18
      uses: actions/setup-node@v1
      with:
        node-version: "18.x"
    - name: Install pnpm
      shell: bash
      run: npm i -g pnpm
    - name: Install dependencies
      shell: bash
      run: pnpm install
