name: Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run linting
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run tests
        run: pnpm test:coverage

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run build
        run: pnpm audit

  deploy:
    runs-on: ubuntu-latest
    needs: [ lint, test, security-scan ]
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
